# Generated by Django 4.2.1 on 2025-06-20 22:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenazas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Describa la amenaza', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cod_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=5)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('identificacion', models.CharField(blank=True, max_length=30)),
                ('fabricante', models.CharField(blank=True, max_length=30)),
                ('url', models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('cont_int', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('tel_lab', models.CharField(blank=True, max_length=30)),
                ('cel_lab', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos_PC_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('cont_int', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('correo', models.CharField(blank=True, max_length=50)),
                ('tel_lab', models.CharField(blank=True, max_length=30)),
                ('cel_lab', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Escenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Describa el escenarios', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Describa la Estrategia', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(null=True)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('fono_t', models.CharField(blank=True, max_length=50)),
                ('fono_c', models.CharField(blank=True, max_length=50)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.area')),
                ('cod_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.cod_area')),
                ('user_gestor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['apellido'],
            },
        ),
        migrations.CreateModel(
            name='Impactos_Asig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_proc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Impactos_Asig_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_proc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_Asig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_proc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_Asig_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_proc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('metodo_acceso', models.CharField(blank=True, max_length=300)),
                ('valor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('hora', models.TimeField(default=datetime.time(18, 49, 32, 217587))),
                ('seccion', models.CharField(blank=True, max_length=2)),
                ('campo', models.CharField(blank=True, max_length=200)),
                ('comentario', models.TextField()),
                ('resuelto', models.BooleanField(blank=True, default=False)),
                ('gestor_aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.gestor')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='LogAut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proceso', models.CharField(blank=True, max_length=10)),
                ('p_status', models.CharField(blank=True, max_length=2)),
                ('fecha', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('Aprobado', models.BooleanField(blank=True, default=False)),
                ('item', models.CharField(blank=True, max_length=10)),
                ('observacion', models.TextField(max_length=200)),
                ('gestor_aprobador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Parametros_G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('valor_1', models.CharField(blank=True, max_length=15)),
                ('valor_2', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasos_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('nro_paso', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('tiempo_esp', models.IntegerField(default=0)),
                ('ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.gestor')),
            ],
            options={
                'ordering': ['nro_paso'],
            },
        ),
        migrations.CreateModel(
            name='Pasos_PC_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('nro_paso', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('tiempo_esp', models.IntegerField(default=0)),
                ('ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.gestor')),
            ],
            options={
                'ordering': ['nro_paso'],
            },
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=25)),
                ('pk_padre', models.IntegerField(default=0)),
                ('fecha_c', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('fecha_ult_mod', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estrategia', models.CharField(max_length=400)),
                ('esta_activo', models.BooleanField(default=False)),
                ('esta_confirmado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('status', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado/Vigente'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', help_text='Estado de la definicion del Proceso', max_length=1)),
                ('existe_p_vigente', models.BooleanField(default=False)),
                ('bck_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_ejecutor', to='bcp.gestor')),
                ('bck_enlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_enlace', to='bcp.gestor')),
                ('bck_resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_resp', to='bcp.gestor')),
                ('contactos_pc', models.ManyToManyField(to='bcp.contactos_pc')),
                ('enlace_c_crisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlace_c_crisis', to='bcp.gestor')),
                ('escenarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_en_procedimiento', to='bcp.escenarios')),
                ('gestor_consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_consultor', to='bcp.gestor')),
                ('gestor_ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_ejecutor', to='bcp.gestor')),
                ('log_auth', models.ManyToManyField(to='bcp.logaut')),
                ('pasos', models.ManyToManyField(to='bcp.pasos_pc')),
                ('resp_proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp_proceso', to='bcp.gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimientos_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=25)),
                ('pk_padre', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=0)),
                ('fecha_c', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('fecha_ult_mod', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('estrategia', models.CharField(max_length=400)),
                ('esta_activo', models.BooleanField(default=False)),
                ('esta_confirmado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('bck_ejecutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_ejecutor_v', to='bcp.gestor')),
                ('bck_enlace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_enlace_v', to='bcp.gestor')),
                ('bck_resp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_resp_v', to='bcp.gestor')),
                ('contactos_pc', models.ManyToManyField(to='bcp.contactos_pc_v')),
                ('enlace_c_crisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlace_c_crisis_v', to='bcp.gestor')),
                ('escenarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escenarios_en_procedimiento_v', to='bcp.escenarios')),
                ('gestor_consultor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_consultor_v', to='bcp.gestor')),
                ('gestor_ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_ejecutor_v', to='bcp.gestor')),
                ('log_auth', models.ManyToManyField(to='bcp.logaut')),
                ('pasos', models.ManyToManyField(to='bcp.pasos_pc_v')),
                ('resp_proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp_proceso_v', to='bcp.gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rec', models.CharField(blank=True, max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Describa el Recurso', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=400)),
                ('contacto', models.CharField(max_length=50)),
                ('contacto_bck', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios_PC_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=400)),
                ('contacto', models.CharField(max_length=50)),
                ('contacto_bck', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Disp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('resumen', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'ordering': ['ponderacion'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Impacto_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'ordering': ['ponderacion'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Indicador_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=400)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Proc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_RR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('descripcion', models.TextField(blank=True, help_text='Describa el Recurso', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('resumen', models.CharField(blank=True, max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SubProceso_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('objetivo', models.TextField(blank=True, help_text='Describa el principal objetivo del Proceso', max_length=500)),
                ('version', models.IntegerField(default=0)),
                ('pk_padre', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('fecha_ult_aut', models.DateField(blank=True, null=True)),
                ('ranking', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('nro_prdto', models.IntegerField(default=0)),
                ('escenarios', models.ManyToManyField(to='bcp.escenarios')),
                ('gestor_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_v_a', to='bcp.gestor')),
                ('gestor_C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_v_c', to='bcp.gestor')),
                ('gestor_I', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_v_i', to='bcp.gestor')),
                ('gestor_R', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_v_r', to='bcp.gestor')),
                ('impact_subp', models.ManyToManyField(blank=True, related_name='impactos_v', to='bcp.impactos_asig_v')),
                ('indicador_subp', models.ManyToManyField(blank=True, related_name='indicadores_v', to='bcp.indicadores_asig_v')),
                ('log_revision', models.ManyToManyField(blank=True, to='bcp.log_revision')),
                ('procedimientos_contingencia', models.ManyToManyField(blank=True, to='bcp.procedimientos')),
                ('procedimientos_contingencia_v', models.ManyToManyField(blank=True, to='bcp.procedimientos_v')),
                ('recursos', models.ManyToManyField(to='bcp.recursos')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='SubProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_padre', models.IntegerField(default=0)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('ranking', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'x Vigentear R'), ('A', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', help_text='Estado de la definicion del Proceso', max_length=1)),
                ('fase_status', models.CharField(blank=True, choices=[('M', 'Fase Procesos'), ('V', 'Fase BIA'), ('B', 'Fase Activos'), ('E', 'Fase Escenarios')], default='M', help_text='Fase del bcp', max_length=1)),
                ('nro_prdto', models.IntegerField(default=0)),
                ('actualiza', models.BooleanField(default=False)),
                ('escenarios', models.ManyToManyField(to='bcp.escenarios')),
                ('gestor_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_a', to='bcp.gestor')),
                ('gestor_C', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_c', to='bcp.gestor')),
                ('gestor_I', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_i', to='bcp.gestor')),
                ('gestor_R', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproceso_r', to='bcp.gestor')),
                ('impact_subp', models.ManyToManyField(blank=True, related_name='impactos', to='bcp.impactos_asig')),
                ('indicador_subp', models.ManyToManyField(blank=True, related_name='indicadores', to='bcp.indicadores_asig')),
                ('log_revision', models.ManyToManyField(blank=True, to='bcp.log_revision')),
                ('recursos', models.ManyToManyField(to='bcp.recursos')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.AddField(
            model_name='recursos',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_rr'),
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=200)),
                ('proceso_padre', models.CharField(blank=True, max_length=30)),
                ('pk_padre', models.IntegerField(default=0)),
                ('ni', models.CharField(blank=True, max_length=20)),
                ('proceso', models.CharField(blank=True, max_length=30)),
                ('nro_hijos', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('objetivo', models.TextField(blank=True, help_text='Describa el principal objetivo del Proceso', max_length=500)),
                ('fecha_crea', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('fecha_ult_mod', models.DateField(blank=True, null=True)),
                ('es_subproceso', models.BooleanField(default=False)),
                ('log_auth', models.ManyToManyField(blank=True, to='bcp.logaut')),
                ('subproceso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.subproceso')),
                ('subproceso_v', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.subproceso_v')),
            ],
            options={
                'ordering': ['proceso'],
            },
        ),
        migrations.AddField(
            model_name='procedimientos_v',
            name='servicios_pc',
            field=models.ManyToManyField(to='bcp.servicios_pc_v'),
        ),
        migrations.AddField(
            model_name='procedimientos_v',
            name='subproceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.subproceso_v'),
        ),
        migrations.AddField(
            model_name='procedimientos_v',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_proc'),
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='servicios_pc',
            field=models.ManyToManyField(to='bcp.servicios_pc'),
        ),
        migrations.AddField(
            model_name='procedimientos',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_proc'),
        ),
        migrations.CreateModel(
            name='Nivel_Impacto_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(null=True)),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_impacto')),
            ],
            options={
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Nivel_Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(null=True)),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('descripcion', models.CharField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_impacto')),
            ],
            options={
                'ordering': ['valor'],
            },
        ),
        migrations.AddField(
            model_name='log_revision',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.procedimientos'),
        ),
        migrations.AddField(
            model_name='log_revision',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.proceso'),
        ),
        migrations.CreateModel(
            name='Indicadores_BIA_P',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(null=True)),
                ('nivel', models.CharField(blank=True, max_length=15)),
                ('definicion', models.CharField(blank=True, max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_indicador')),
            ],
        ),
        migrations.CreateModel(
            name='Indicadores_BIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(null=True)),
                ('nivel', models.CharField(blank=True, max_length=15)),
                ('definicion', models.CharField(blank=True, max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.tipo_indicador')),
            ],
        ),
        migrations.AddField(
            model_name='indicadores_asig_v',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador_vigente', to='bcp.tipo_indicador'),
        ),
        migrations.AddField(
            model_name='indicadores_asig_v',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_bia_vigente', to='bcp.indicadores_bia'),
        ),
        migrations.AddField(
            model_name='indicadores_asig',
            name='indicador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicador', to='bcp.tipo_indicador'),
        ),
        migrations.AddField(
            model_name='indicadores_asig',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_bia', to='bcp.indicadores_bia'),
        ),
        migrations.CreateModel(
            name='Incidentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('nombre_r', models.CharField(blank=True, max_length=25)),
                ('area_r', models.CharField(blank=True, max_length=25)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('changed', models.BooleanField(default=False)),
                ('amenazas_i', models.ManyToManyField(to='bcp.amenazas')),
                ('escenarios_i', models.ManyToManyField(to='bcp.escenarios')),
                ('procesos_i', models.ManyToManyField(to='bcp.subproceso')),
            ],
        ),
        migrations.AddField(
            model_name='impactos_asig_v',
            name='impacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgo_vigente', to='bcp.tipo_impacto'),
        ),
        migrations.AddField(
            model_name='impactos_asig_v',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_imp_vigente', to='bcp.nivel_impacto'),
        ),
        migrations.AddField(
            model_name='impactos_asig',
            name='impacto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgo', to='bcp.tipo_impacto'),
        ),
        migrations.AddField(
            model_name='impactos_asig',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_imp', to='bcp.nivel_impacto'),
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='escenarios',
            name='estrategias',
            field=models.ManyToManyField(to='bcp.estrategias'),
        ),
        migrations.CreateModel(
            name='Drp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=8)),
                ('version', models.CharField(default='0000', max_length=5)),
                ('fecha_c', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('fecha_ult_mod', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('introduccion', models.CharField(blank=True, max_length=2000)),
                ('esta_activo', models.BooleanField(default=False)),
                ('status_1', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_2', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_3', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_4', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_5', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_6', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_7', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_A', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', max_length=1)),
                ('status_t', models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], max_length=1)),
                ('desc_estrategia', models.CharField(blank=True, max_length=1000)),
                ('bck_ejecutor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_ejecutor_drp', to='bcp.gestor')),
                ('bck_enlace_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_enlace_drp', to='bcp.gestor')),
                ('bck_resp_drp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_resp_drp', to='bcp.gestor')),
                ('componentes', models.ManyToManyField(to='bcp.componentes')),
                ('contactos_drp', models.ManyToManyField(to='bcp.contactos_pc')),
                ('disposicion_componentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_disp', to='bcp.tipo_disp')),
                ('enlace_c_crisis_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlace_c_crisis_drp', to='bcp.gestor')),
                ('gestor_consultor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_consultor_drp', to='bcp.gestor')),
                ('gestor_ejecutor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_ejecutor_drp', to='bcp.gestor')),
                ('log_auth_drp', models.ManyToManyField(to='bcp.logaut')),
                ('pasos_drp', models.ManyToManyField(to='bcp.pasos_pc')),
                ('procesos_drp', models.ManyToManyField(to='bcp.subproceso')),
                ('resp_drp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp_drp', to='bcp.gestor')),
                ('servicios_drp', models.ManyToManyField(to='bcp.servicios_pc')),
                ('tipo_Site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_site', to='bcp.tipo_site')),
            ],
        ),
        migrations.CreateModel(
            name='Control_Cambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, default=datetime.date(2025, 6, 20), null=True)),
                ('hora', models.TimeField(default=datetime.time(18, 49, 32, 181587))),
                ('descripcion', models.TextField(max_length=200)),
                ('gestor_aut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.gestor')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.procedimientos_v')),
                ('proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.subproceso_v')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.AddField(
            model_name='componentes',
            name='lbc',
            field=models.ManyToManyField(to='bcp.lbc'),
        ),
        migrations.AddField(
            model_name='componentes',
            name='tipo_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_disp', to='bcp.tipo_componente'),
        ),
        migrations.AddField(
            model_name='amenazas',
            name='landscape',
            field=models.ManyToManyField(to='bcp.escenarios'),
        ),
    ]

