# Generated by Django 4.2.1 on 2025-06-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproceso',
            name='actualiza',
            field=models.BooleanField(default=False),
        ),
    ]
