# Generated by Django 4.2.1 on 2025-06-21 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_cambios',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 21)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='control_cambios',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_c',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_ult_mod',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_revision',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_revision',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logaut',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_c',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_ult_mod',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_c',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_ult_mod',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_crea',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_ult_mod',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproceso_v',
            name='fecha_ult_aut',
            field=models.DateField(auto_now_add=True, default='2025-06-20'),
            preserve_default=False,
        ),
    ]
