# Generated by Django 4.2.1 on 2025-03-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos_v',
            name='contactos_pc',
        ),
        migrations.RemoveField(
            model_name='procedimientos_v',
            name='servicios_pc',
        ),
    ]
