# Generated by Django 4.2.1 on 2025-03-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0002_remove_procedimientos_v_contactos_pc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos_v',
            name='contactos_pc',
            field=models.ManyToManyField(to='BCP.contactos_pc_v'),
        ),
        migrations.AddField(
            model_name='procedimientos_v',
            name='servicios_pc',
            field=models.ManyToManyField(to='BCP.servicios_pc_v'),
        ),
    ]
