# Generated by Django 4.2.1 on 2025-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0002_alter_control_cambios_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='es_borrable',
            field=models.BooleanField(default=True),
        ),
    ]
