# Generated by Django 4.2.1 on 2025-06-15 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0002_subproceso_actualiza'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproceso_v',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
