# Generated by Django 4.2.1 on 2025-08-08 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0003_procedimientos_es_borrable'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_revision',
            name='drp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.drp'),
        ),
    ]
