# Generated by Django 4.2.1 on 2025-03-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0003_procedimientos_v_contactos_pc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimientos_v',
            name='pasos',
        ),
    ]
