# Generated by Django 4.2.1 on 2025-08-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0004_log_revision_drp'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategias',
            name='activa_drp',
            field=models.BooleanField(default=False),
        ),
    ]
