# Generated by Django 4.2.1 on 2025-06-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0004_alter_control_cambios_fecha_alter_drp_fecha_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='log_auth',
            field=models.ManyToManyField(blank=True, to='BCP.logaut'),
        ),
        migrations.AlterField(
            model_name='subproceso',
            name='impact_subp',
            field=models.ManyToManyField(blank=True, related_name='impactos', to='BCP.impactos_asig'),
        ),
        migrations.AlterField(
            model_name='subproceso',
            name='indicador_subp',
            field=models.ManyToManyField(blank=True, related_name='indicadores', to='BCP.indicadores_asig'),
        ),
    ]
