# Generated by Django 4.2.1 on 2025-03-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0004_remove_procedimientos_v_pasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos_v',
            name='pasos',
            field=models.ManyToManyField(to='BCP.pasos_pc_v'),
        ),
    ]
