# Generated by Django 4.2.1 on 2025-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0005_estrategias_activa_drp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drp',
            name='procesos_drp',
            field=models.ManyToManyField(to='bcp.subproceso_v'),
        ),
    ]
