# Generated by Django 4.2.1 on 2025-09-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0006_alter_drp_procesos_drp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='procesos_i',
            field=models.ManyToManyField(to='bcp.subproceso_v'),
        ),
    ]
