# Generated by Django 4.2.1 on 2025-06-19 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0006_alter_control_cambios_fecha_alter_drp_fecha_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_cambios',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_crea',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_ult_mod',
            field=models.DateField(blank=True, null=True),
        ),
    ]
