# Generated by Django 4.2.1 on 2025-10-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0007_alter_incidentes_procesos_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drp',
            name='version',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='esta_activo',
        ),
        migrations.RemoveField(
            model_name='procedimientos',
            name='esta_confirmado',
        ),
        migrations.AddField(
            model_name='drp',
            name='modo_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidentes',
            name='test',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Drp_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=8)),
                ('version', models.CharField(default='0000', max_length=5)),
                ('fecha_c', models.DateField(auto_now_add=True)),
                ('fecha_auth', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('introduccion', models.CharField(blank=True, max_length=2000)),
                ('esta_activo', models.BooleanField(default=False)),
                ('esta_confirmado', models.BooleanField(default=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos/')),
                ('desc_estrategia', models.CharField(blank=True, max_length=1000)),
                ('bck_ejecutor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_ejecutor_drp_v', to='bcp.gestor')),
                ('bck_enlace_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_enlace_drp_v', to='bcp.gestor')),
                ('bck_resp_drp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bck_resp_drp_v', to='bcp.gestor')),
                ('componentes', models.ManyToManyField(to='bcp.componentes')),
                ('contactos_drp', models.ManyToManyField(to='bcp.contactos_pc')),
                ('disposicion_componentes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_disp_v', to='bcp.tipo_disp')),
                ('enlace_c_crisis_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enlace_c_crisis_drp_v', to='bcp.gestor')),
                ('gestor_consultor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_consultor_drp_v', to='bcp.gestor')),
                ('gestor_ejecutor_drp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestor_ejecutor_drp_v', to='bcp.gestor')),
                ('log_auth_drp', models.ManyToManyField(to='bcp.logaut')),
                ('pasos_drp', models.ManyToManyField(to='bcp.pasos_pc')),
                ('procesos_drp', models.ManyToManyField(to='bcp.subproceso_v')),
                ('resp_drp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resp_drp_v', to='bcp.gestor')),
                ('servicios_drp', models.ManyToManyField(to='bcp.servicios_pc')),
                ('tipo_Site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_site_v', to='bcp.tipo_site')),
            ],
        ),
    ]
