# Generated by Django 4.2.1 on 2025-06-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0007_alter_control_cambios_fecha_alter_proceso_fecha_crea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control_cambios',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_c',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_ult_mod',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_c',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_ult_mod',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_c',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_ult_mod',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_crea',
            field=models.DateTimeField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_ult_mod',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproceso_v',
            name='fecha_ult_aut',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
