# Generated by Django 4.2.1 on 2025-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0008_remove_drp_version_remove_procedimientos_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentes',
            name='codigo_inv',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
