# Generated by Django 4.2.1 on 2025-11-04 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0009_componentes_codigo_inv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.procedimientos_v')),
            ],
        ),
        migrations.AlterModelOptions(
            name='recursos',
            options={'ordering': ['tipo', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='tipo_rr',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='tipo_rr',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Pasos_Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=400)),
                ('terminado', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.checklist')),
                ('paso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.pasos_pc_v')),
            ],
        ),
    ]
