# Generated by Django 4.2.1 on 2025-11-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0010_checklist_alter_recursos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasos_check',
            name='comentario',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.CreateModel(
            name='Check_Pasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=400)),
                ('terminado', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.checklist')),
                ('paso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.pasos_pc_v')),
            ],
        ),
    ]
