# Generated by Django 4.2.1 on 2025-06-20 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0010_alter_control_cambios_fecha_alter_drp_fecha_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_cambios',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 44, 17, 702201)),
        ),
        migrations.AddField(
            model_name='log_revision',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 44, 17, 749724)),
        ),
        migrations.AlterField(
            model_name='control_cambios',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_c',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='drp',
            name='fecha_ult_mod',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='log_revision',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='logaut',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_c',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='fecha_ult_mod',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_c',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='procedimientos_v',
            name='fecha_ult_mod',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_crea',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 19), null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='fecha_ult_mod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproceso_v',
            name='fecha_ult_aut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
