# Generated by Django 4.2.1 on 2025-11-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0011_alter_pasos_check_comentario_check_pasos'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_pasos',
            name='fecha_ter',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pasos_Check',
        ),
    ]
