# Generated by Django 4.2.1 on 2025-06-20 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCP', '0011_control_cambios_hora_log_revision_hora_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control_cambios',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='log_revision',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterField(
            model_name='control_cambios',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 46, 25, 930892)),
        ),
        migrations.AlterField(
            model_name='log_revision',
            name='hora',
            field=models.TimeField(default=datetime.time(20, 46, 25, 962575)),
        ),
    ]
