# Generated by Django 4.2.1 on 2025-11-05 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0012_check_pasos_fecha_ter_checklist_completado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.AddField(
            model_name='checklist',
            name='incidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.incidentes'),
        ),
        migrations.AlterField(
            model_name='check_pasos',
            name='fecha_ter',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
