# Generated by Django 4.2.1 on 2025-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0013_alter_checklist_options_checklist_incidente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentes',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
