# Generated by Django 4.2.1 on 2025-11-07 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0014_incidentes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
