# Generated by Django 4.2.1 on 2025-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0015_incidentes_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='nro_chk',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='procedimientos_v',
            name='correlativo_chk',
            field=models.IntegerField(default=0),
        ),
    ]
