# Generated by Django 4.2.1 on 2025-11-09 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0016_checklist_nro_chk_procedimientos_v_correlativo_chk'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_revision',
            name='procedimiento_v',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcp.procedimientos_v'),
        ),
    ]
