# Generated by Django 4.2.1 on 2025-11-11 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcp', '0017_log_revision_procedimiento_v'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruebaContingencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField(blank=True, null=True)),
                ('criterios_exito', models.TextField(blank=True, null=True)),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ejecución', 'En ejecución'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='bcp.procedimientos_v')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prueba de Contingencia',
                'verbose_name_plural': 'Pruebas de Contingencia',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_real', models.DateTimeField()),
                ('descripcion_ejecucion', models.TextField()),
                ('resultados_obtenidos', models.TextField(blank=True, null=True)),
                ('incidentes', models.TextField(blank=True, null=True)),
                ('evaluacion_final', models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Parcial', 'Parcial'), ('Fallida', 'Fallida')], max_length=20, null=True)),
                ('lecciones_aprendidas', models.TextField(blank=True, null=True)),
                ('evidencia_general', models.FileField(blank=True, null=True, upload_to='evidencias_pruebas/')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='bcp.pruebacontingencia')),
            ],
            options={
                'verbose_name': 'Ejecución de Prueba',
                'verbose_name_plural': 'Ejecuciones de Pruebas',
                'ordering': ['-fecha_real'],
            },
        ),
        migrations.CreateModel(
            name='CasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('precondiciones', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='bcp.pruebacontingencia')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
                'ordering': ['prueba', 'numero'],
                'unique_together': {('prueba', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EjecucionCasoPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Fallida', 'Fallida'), ('Parcial', 'Parcial')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias_casos/')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='bcp.casoprueba')),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_ejecutados', to='bcp.ejecucionprueba')),
            ],
            options={
                'verbose_name': 'Ejecución de Caso de Prueba',
                'verbose_name_plural': 'Ejecuciones de Casos de Prueba',
                'unique_together': {('ejecucion', 'caso')},
            },
        ),
    ]
