# Generated by Django 4.2.1 on 2025-11-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0018_pruebacontingencia_ejecucionprueba_casoprueba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebacontingencia',
            old_name='nombre',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='pruebacontingencia',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.gestor'),
        ),
    ]
