# Generated by Django 4.2.1 on 2025-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0019_rename_nombre_pruebacontingencia_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimientos',
            name='corr_prbas',
            field=models.IntegerField(default=0),
        ),
    ]
