# Generated by Django 4.2.1 on 2025-11-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0020_procedimientos_corr_prbas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebacontingencia',
            name='procedimiento',
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='corr_prbas',
            field=models.IntegerField(default=1),
        ),
    ]
