# Generated by Django 4.2.1 on 2025-11-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0021_remove_pruebacontingencia_procedimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebacontingencia',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='bcp.procedimientos'),
        ),
    ]
