# Generated by Django 4.2.1 on 2025-11-14 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0022_pruebacontingencia_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruebacontingencia',
            name='fecha_programada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
