# Generated by Django 4.2.1 on 2025-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0023_alter_pruebacontingencia_fecha_programada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebacontingencia',
            name='corr_casos',
            field=models.IntegerField(default=0),
        ),
    ]
