# Generated by Django 4.2.1 on 2025-11-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0024_pruebacontingencia_corr_casos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruebacontingencia',
            name='corr_casos',
        ),
    ]
