# Generated by Django 4.2.1 on 2025-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0025_remove_pruebacontingencia_corr_casos'),
    ]

    operations = [
        migrations.AddField(
            model_name='casoprueba',
            name='codigo',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
