# Generated by Django 4.2.1 on 2025-11-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0026_casoprueba_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casoprueba',
            options={'ordering': ['prueba', 'codigo'], 'verbose_name': 'Caso de Prueba', 'verbose_name_plural': 'Casos de Prueba'},
        ),
        migrations.AlterUniqueTogether(
            name='casoprueba',
            unique_together={('prueba', 'codigo')},
        ),
        migrations.RemoveField(
            model_name='casoprueba',
            name='numero',
        ),
    ]
