# Generated by Django 4.2.1 on 2025-11-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0027_alter_casoprueba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruebacontingencia',
            name='corr_casos',
            field=models.IntegerField(default=0),
        ),
    ]
