# Generated by Django 4.2.1 on 2025-12-01 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0028_pruebacontingencia_corr_casos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casoprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba_des', to='bcp.pruebacontingencia'),
        ),
        migrations.AlterField(
            model_name='pruebacontingencia',
            name='procedimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_des', to='bcp.procedimientos'),
        ),
        migrations.CreateModel(
            name='PruebaContingencia_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField(blank=True, null=True)),
                ('criterios_exito', models.TextField(blank=True, null=True)),
                ('fecha_programada', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En ejecución', 'En ejecución'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('corr_casos', models.IntegerField(default=0)),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos_vigente', to='bcp.procedimientos_v')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.gestor')),
            ],
            options={
                'verbose_name': 'Prueba de Contingencia',
                'verbose_name_plural': 'Pruebas de Contingencia',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='CasoPrueba_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='0000', max_length=4)),
                ('descripcion', models.TextField()),
                ('resultado_esperado', models.TextField()),
                ('precondiciones', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10)),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba_vigente', to='bcp.pruebacontingencia_v')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
                'ordering': ['prueba', 'codigo'],
                'unique_together': {('prueba', 'codigo')},
            },
        ),
    ]
