# Generated by Django 4.2.1 on 2025-12-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0029_alter_casoprueba_prueba_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-nro_chk']},
        ),
        migrations.AddField(
            model_name='ejecucionprueba',
            name='nro_ejecucion',
            field=models.CharField(default='0000', max_length=5),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='nro_chk',
            field=models.CharField(default='0000', max_length=5),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incidentes',
            name='fecha_creacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='procedimientos',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'Vigenteado'), ('r', 'X Vigentear R'), ('A', 'Aprobado'), ('a', 'x Aprobar A'), ('C', 'En Dfncn C'), ('x', 'En Revision C')], default='C', help_text='Estado de la definicion del Proceso', max_length=1),
        ),
    ]
