# Generated by Django 4.2.1 on 2025-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0030_alter_checklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucioncasoprueba',
            name='nro_ejecucion',
            field=models.CharField(default='0000', max_length=7),
        ),
    ]
