# Generated by Django 4.2.1 on 2025-12-13 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0031_ejecucioncasoprueba_nro_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='fecha_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='bcp.pruebacontingencia_v'),
        ),
    ]
