# Generated by Django 4.2.1 on 2025-12-13 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0032_alter_ejecucionprueba_fecha_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucioncasoprueba',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='bcp.casoprueba_v'),
        ),
    ]
