# Generated by Django 4.2.1 on 2025-12-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0033_alter_ejecucioncasoprueba_caso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionprueba',
            name='incidente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.incidentes'),
        ),
    ]
