# Generated by Django 4.2.1 on 2025-12-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0034_ejecucionprueba_incidente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejecucionprueba',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcp.checklist'),
        ),
    ]
