# Generated by Django 4.2.1 on 2025-12-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0035_ejecucionprueba_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionprueba',
            name='evaluacion_final',
            field=models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Parcial', 'Parcial'), ('Fallida', 'Fallida'), ('En Ejecucion', 'En Ejecucion')], default='En Ejecucion', max_length=20, null=True),
        ),
    ]
