# Generated by Django 4.2.1 on 2025-12-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0036_alter_ejecucionprueba_evaluacion_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucioncasoprueba',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Fallida', 'Fallida'), ('Parcial', 'Parcial'), ('En Proceso...', 'En En Proceso...'), ('No Aplica', 'No Aplica')], default='En Aplicacion', max_length=20, null=True),
        ),
    ]
