# Generated by Django 4.2.1 on 2025-12-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0037_alter_ejecucioncasoprueba_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucioncasoprueba',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Fallida', 'Fallida'), ('Parcial', 'Parcial'), ('En Proceso', 'En Proceso'), ('No Aplica', 'No Aplica')], default='En Proceso', max_length=20, null=True),
        ),
    ]
