# Generated by Django 4.2.1 on 2026-01-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0039_alter_ejecucioncasoprueba_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ejecucioncasoprueba',
            name='resultado',
            field=models.CharField(blank=True, choices=[('Exitosa', 'Exitosa'), ('Fallida', 'Fallida'), ('Parcial', 'Parcial'), ('En Proceso', 'En Proceso'), ('No Aplica', 'No Aplica')], default='En Proceso', max_length=20, null=True),
        ),
    ]
