# Generated by Django 4.2.1 on 2026-01-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcp', '0040_gestor_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
